/**
 * MANA CALENDAR 2027 — VERIFIED 2027 FESTIVALS & HOLIDAYS DATASET
 * Comprehensive, verified astronomical & cultural dates for Andhra Pradesh & Telangana.
 */

import type { Festival } from '@mana/types';

export const VERIFIED_FESTIVALS_2027: Festival[] = [
  // --- JANUARY 2027 ---
  {
    id: 'f-2027-01-01',
    calendar_date: '2027-01-01',
    name_en: "New Year's Day",
    name_te: 'నూతన సంవత్సర దినోత్సవం',
    festival_type: 'national',
    is_holiday: true,
    holiday_type: 'restricted',
    importance: 'normal',
    tag: 'holiday',
    description_en: 'First day of Gregorian Year 2027',
    description_te: '2027 ఆంగ్ల నూతన సంవత్సర ప్రారంభ దినం',
  },
  {
    id: 'f-2027-01-14',
    calendar_date: '2027-01-14',
    name_en: 'Bhogi Panduga',
    name_te: 'భోగి పండుగ',
    festival_type: 'regional',
    is_holiday: true,
    holiday_type: 'regional_ap',
    importance: 'major',
    tag: 'sankranti',
    description_en: 'First day of the 4-day Sankranti harvest festival with traditional Bhogi bonfires.',
    description_te: 'సంక్రాంతి పండుగ మొదటి రోజు భోగి మంటలు మరియు సంబరాలు.',
  },
  {
    id: 'f-2027-01-15',
    calendar_date: '2027-01-15',
    name_en: 'Makara Sankranti / Pedda Panduga',
    name_te: 'మకర సంక్రాంతి / పెద్ద పండుగ',
    festival_type: 'hindu',
    is_holiday: true,
    holiday_type: 'gazetted',
    importance: 'major',
    tag: 'sankranti',
    description_en: 'Sun enters Makara Rashi; major Telugu harvest festival and Uttarayana beginning.',
    description_te: 'సూర్యుడు మకర రాశిలోకి ప్రవేశించే పవిత్ర పర్వదినం. పంటల పండుగ, పిండివంటలు మరియు బంధుమిత్రుల కలయిక.',
  },
  {
    id: 'f-2027-01-16',
    calendar_date: '2027-01-16',
    name_en: 'Kanuma Panduga',
    name_te: 'కనుమ పండుగ',
    festival_type: 'regional',
    is_holiday: true,
    holiday_type: 'regional_ap',
    importance: 'major',
    tag: 'sankranti',
    description_en: 'Cattle worship day celebrating farm livestock and rural agriculture.',
    description_te: 'రైతుల నేస్తాలైన పశువులను పూజించే పవిత్ర దినం.',
  },
  {
    id: 'f-2027-01-17',
    calendar_date: '2027-01-17',
    name_en: 'Mukkanuma',
    name_te: 'ముక్కనుమ',
    festival_type: 'cultural',
    is_holiday: false,
    importance: 'normal',
    tag: 'sankranti',
    description_en: 'Fourth day of the festive Sankranti season in Andhra Pradesh.',
    description_te: 'సంక్రాంతి ఉత్సవాల నాల్గవ రోజు.',
  },
  {
    id: 'f-2027-01-18',
    calendar_date: '2027-01-18',
    name_en: 'Putrada Ekadashi',
    name_te: 'పుత్రదా ఏకాదశి',
    festival_type: 'hindu',
    importance: 'medium',
    tag: 'ekadashi',
    description_en: 'Auspicious Ekadashi fast dedicated to Lord Vishnu.',
    description_te: 'శ్రీ మహావిష్ణువుకు అంకితమైన పవిత్ర ఏకాదశి వ్రతం.',
  },
  {
    id: 'f-2027-01-22',
    calendar_date: '2027-01-22',
    name_en: 'Pausha Purnima',
    name_te: 'పుష్య పౌర్ణమి',
    festival_type: 'hindu',
    importance: 'medium',
    tag: 'purnima',
    description_en: 'Full moon day of Pushya month with sacred river baths.',
    description_te: 'పుష్య మాస పౌర్ణమి పుణ్యస్నానాలు.',
  },
  {
    id: 'f-2027-01-26',
    calendar_date: '2027-01-26',
    name_en: 'Republic Day',
    name_te: 'భారత గణతంత్ర దినోత్సవం',
    festival_type: 'national',
    is_holiday: true,
    holiday_type: 'gazetted',
    importance: 'major',
    tag: 'holiday',
    description_en: 'Celebration of the Constitution of India.',
    description_te: 'భారత రాజ్యాంగం అమలులోకి వచ్చిన జాతీయ పర్వదినం.',
  },

  // --- FEBRUARY 2027 ---
  {
    id: 'f-2027-02-06',
    calendar_date: '2027-02-06',
    name_en: 'Magha Amavasya (Mauni Amavasya)',
    name_te: 'మాఘ అమావాస్య (మౌని అమావాస్య)',
    festival_type: 'hindu',
    importance: 'medium',
    tag: 'amavasya',
    description_en: 'Sacred new moon day of Magha month for ancestral offerings.',
    description_te: 'పితృదేవతలకు తర్పణాలు సమర్పించే పవిత్ర మాఘ అమావాస్య.',
  },
  {
    id: 'f-2027-02-12',
    calendar_date: '2027-02-12',
    name_en: 'Ratha Saptami (Surya Jayanti)',
    name_te: 'రథసప్తమి (సూర్య జయంతి)',
    festival_type: 'hindu',
    is_holiday: false,
    importance: 'major',
    tag: 'festival',
    description_en: 'Worship of the Sun God Surya riding his 7-horse chariot on his birthday.',
    description_te: 'సూర్యభగవానుని జన్మదినం, ఆవుపాలతో పరమాన్నం వండే పుణ్యదినం.',
  },
  {
    id: 'f-2027-02-14',
    calendar_date: '2027-02-14',
    name_en: 'Kumbha Sankranti',
    name_te: 'కుంభ సంక్రాంతి',
    festival_type: 'hindu',
    importance: 'normal',
    tag: 'sankranti',
    description_en: 'Sun transit into Kumbha Rashi.',
    description_te: 'సూర్యుడు కుంభ రాశిలోకి ప్రవేశించే పుణ్యకాలం.',
  },
  {
    id: 'f-2027-02-17',
    calendar_date: '2027-02-17',
    name_en: 'Jaya Ekadashi',
    name_te: 'జయ ఏకాదశి',
    festival_type: 'hindu',
    importance: 'medium',
    tag: 'ekadashi',
    description_en: 'Auspicious Ekadashi vrata.',
    description_te: 'పాప విమోచన జయ ఏకాదశి వ్రతం.',
  },
  {
    id: 'f-2027-02-21',
    calendar_date: '2027-02-21',
    name_en: 'Magha Purnima (Maha Maghi)',
    name_te: 'మాఘ పౌర్ణమి (మహా మాఘి)',
    festival_type: 'hindu',
    importance: 'medium',
    tag: 'purnima',
    description_en: 'Full moon of Magha month with holy dips in rivers and oceans.',
    description_te: 'సముద్ర స్నానాలు మరియు నదీ స్నానాలు ఆచరించే పవిత్ర పౌర్ణమి.',
  },

  // --- MARCH 2027 ---
  {
    id: 'f-2027-03-06',
    calendar_date: '2027-03-06',
    name_en: 'Maha Shivaratri',
    name_te: 'మహా శివరాత్రి',
    festival_type: 'hindu',
    is_holiday: true,
    holiday_type: 'gazetted',
    importance: 'major',
    tag: 'festival',
    description_en: 'Grand celebration dedicated to Lord Shiva with night-long vigil (Jagaran) and Lingodbhava.',
    description_te: 'శివనామస్మరణ, అభిషేకాలు మరియు రాత్రి జాగరణలతో జరుపుకునే పవిత్ర మహా పర్వదినం.',
  },
  {
    id: 'f-2027-03-08',
    calendar_date: '2027-03-08',
    name_en: 'Phalguna Amavasya',
    name_te: 'ఫాల్గుణ అమావాస్య',
    festival_type: 'hindu',
    importance: 'normal',
    tag: 'amavasya',
    description_en: 'New moon day of Phalguna month.',
    description_te: 'ఫాల్గుణ మాస అమావాస్య.',
  },
  {
    id: 'f-2027-03-15',
    calendar_date: '2027-03-15',
    name_en: 'Meena Sankranti',
    name_te: 'మీన సంక్రాంతి',
    festival_type: 'hindu',
    importance: 'normal',
    tag: 'sankranti',
    description_en: 'Sun transit into Meena Rashi.',
    description_te: 'సూర్యుడు మీన రాశిలోకి ప్రవేశించే సమయం.',
  },
  {
    id: 'f-2027-03-18',
    calendar_date: '2027-03-18',
    name_en: 'Amalaki Ekadashi',
    name_te: 'ఆమలకీ ఏకాదశి',
    festival_type: 'hindu',
    importance: 'medium',
    tag: 'ekadashi',
    description_en: 'Worship of Lord Vishnu and sacred Amla tree.',
    description_te: 'ఉసిరి వృక్షాన్ని పూజించే పవిత్ర ఏకాదశి.',
  },
  {
    id: 'f-2027-03-22',
    calendar_date: '2027-03-22',
    name_en: 'Holika Dahan / Kama Dahana',
    name_te: 'కామ దహనం / హోలికా దహన్',
    festival_type: 'hindu',
    importance: 'medium',
    tag: 'festival',
    description_en: 'Bonfire ritual marking triumph of righteousness over evil.',
    description_te: 'చెడుపై మంచి సాధించిన విజయానికి గుర్తుగా భోగి మంటలు.',
  },
  {
    id: 'f-2027-03-23',
    calendar_date: '2027-03-23',
    name_en: 'Holi (Festival of Colors)',
    name_te: 'హోలీ (రంగుల పండుగ)',
    festival_type: 'hindu',
    is_holiday: true,
    holiday_type: 'gazetted',
    importance: 'major',
    tag: 'festival',
    description_en: 'Joyous national festival of vibrant colors and spring celebration.',
    description_te: 'వసంతోత్సవం మరియు స్నేహభావాన్ని చాటే రంగుల పండుగ.',
  },
  {
    id: 'f-2027-03-23-p',
    calendar_date: '2027-03-23',
    name_en: 'Phalguna Purnima (Lakshmi Jayanti)',
    name_te: 'ఫాల్గుణ పౌర్ణమి (లక్ష్మీ జయంతి)',
    festival_type: 'hindu',
    importance: 'medium',
    tag: 'purnima',
    description_en: 'Appearance day of Goddess Mahalakshmi during Samudra Manthan.',
    description_te: 'శ్రీ మహాలక్ష్మి అవతరించిన పవిత్ర పౌర్ణమి దినం.',
  },

  // --- APRIL 2027 ---
  {
    id: 'f-2027-04-07',
    calendar_date: '2027-04-07',
    name_en: 'Sri Plavanga Nama Ugadi (Telugu New Year)',
    name_te: 'శ్రీ ప్లవంగ నామ ఉగాది (తెలుగు నూతన సంవత్సరం)',
    festival_type: 'regional',
    is_holiday: true,
    holiday_type: 'gazetted',
    importance: 'major',
    tag: 'festival',
    description_en: 'Beginning of Sri Plavanga Nama Samvatsara; celebrated with Ugadi Pachadi and Panchanga Sravanam.',
    description_te: 'తెలుగువారి నూతన సంవత్సర ప్రారంభం; షడ్రుచుల ఉగాది పచ్చడి మరియు పంచాంగ శ్రవణం.',
  },
  {
    id: 'f-2027-04-14',
    calendar_date: '2027-04-14',
    name_en: 'Dr. B.R. Ambedkar Jayanti',
    name_te: 'డా. బి.ఆర్. అంబేద్కర్ జయంతి',
    festival_type: 'national',
    is_holiday: true,
    holiday_type: 'gazetted',
    importance: 'major',
    tag: 'holiday',
    description_en: 'Birth anniversary of the architect of the Indian Constitution.',
    description_te: 'భారత రాజ్యాంగ నిర్మాత బాబాసాహెబ్ అంబేద్కర్ జయంతి.',
  },
  {
    id: 'f-2027-04-14-s',
    calendar_date: '2027-04-14',
    name_en: 'Mesha Sankranti (Solar New Year)',
    name_te: 'మేష సంక్రాంతి (సౌరమాన నూతన సంవత్సరం)',
    festival_type: 'hindu',
    importance: 'medium',
    tag: 'sankranti',
    description_en: 'Sun enters Mesha (Aries) starting the sidereal solar year.',
    description_te: 'సూర్యుడు మేష రాశిలోకి ప్రవేశించే సౌర నూతన సంవత్సరం.',
  },
  {
    id: 'f-2027-04-16',
    calendar_date: '2027-04-16',
    name_en: 'Sri Rama Navami',
    name_te: 'శ్రీరామ నవమి',
    festival_type: 'hindu',
    is_holiday: true,
    holiday_type: 'gazetted',
    importance: 'major',
    tag: 'festival',
    description_en: 'Celebration of the birth and divine wedding (Kalyanam) of Lord Sri Rama in Bhadrachalam and temples.',
    description_te: 'భద్రాచలం సహా ఆలయాల్లో సీతారాముల దివ్య కల్యాణ మహోత్సవం.',
  },
  {
    id: 'f-2027-04-17',
    calendar_date: '2027-04-17',
    name_en: 'Kamada Ekadashi',
    name_te: 'కామదా ఏకాదశి',
    festival_type: 'hindu',
    importance: 'medium',
    tag: 'ekadashi',
    description_en: 'Chaitra Shukla Ekadashi fulfilling devotees desires.',
    description_te: 'కోరికలను నెరవేర్చే కామదా ఏకాదశి వ్రతం.',
  },
  {
    id: 'f-2027-04-21',
    calendar_date: '2027-04-21',
    name_en: 'Chaitra Purnima (Hanuman Jayanti North)',
    name_te: 'చైత్ర పౌర్ణమి (చిత్రగుప్త పూజ)',
    festival_type: 'hindu',
    importance: 'medium',
    tag: 'purnima',
    description_en: 'Full moon day of Chaitra month.',
    description_te: 'చైత్ర పౌర్ణమి మరియు చిత్రగుప్త పూజ.',
  },

  // --- MAY 2027 ---
  {
    id: 'f-2027-05-01',
    calendar_date: '2027-05-01',
    name_en: 'May Day (Labor Day)',
    name_te: 'కార్మికుల దినోత్సవం (మే డే)',
    festival_type: 'national',
    is_holiday: true,
    holiday_type: 'gazetted',
    importance: 'medium',
    tag: 'holiday',
    description_en: 'International Workers Day celebration.',
    description_te: 'శ్రామిక దినోత్సవం.',
  },
  {
    id: 'f-2027-05-06',
    calendar_date: '2027-05-06',
    name_en: 'Vaishakha Amavasya',
    name_te: 'వైశాఖ అమావాస్య',
    festival_type: 'hindu',
    importance: 'normal',
    tag: 'amavasya',
    description_en: 'New moon of Vaishakha month.',
    description_te: 'వైశాఖ మాస అమావాస్య.',
  },
  {
    id: 'f-2027-05-15',
    calendar_date: '2027-05-15',
    name_en: 'Vrishabha Sankranti',
    name_te: 'వృషభ సంక్రాంతి',
    festival_type: 'hindu',
    importance: 'normal',
    tag: 'sankranti',
    description_en: 'Sun transit into Taurus.',
    description_te: 'సూర్యుడు వృషభ రాశిలోకి ప్రవేశం.',
  },
  {
    id: 'f-2027-05-16',
    calendar_date: '2027-05-16',
    name_en: 'Mohini Ekadashi',
    name_te: 'మోహినీ ఏకాదశి',
    festival_type: 'hindu',
    importance: 'medium',
    tag: 'ekadashi',
    description_en: 'Honoring Lord Vishnu Mohini avatar.',
    description_te: 'శ్రీహరి మోహినీ అవతార స్మరణ.',
  },
  {
    id: 'f-2027-05-20',
    calendar_date: '2027-05-20',
    name_en: 'Telugu Hanuman Jayanti',
    name_te: 'తెలుగు హనుమాన్ జయంతి',
    festival_type: 'regional',
    is_holiday: false,
    importance: 'major',
    tag: 'festival',
    description_en: 'Celebrated in AP & Telangana concluding 41 days of Hanuman deeksha on Vaishakha Bahula Dashami.',
    description_te: '41 రోజుల హనుమాన్ దీక్షల ముగింపు మరియు ఆంజనేయ స్వామి జయంతి.',
  },
  {
    id: 'f-2027-05-21',
    calendar_date: '2027-05-21',
    name_en: 'Buddha Purnima (Vaishakha Purnima)',
    name_te: 'బుద్ధ పౌర్ణమి (వైశాఖ పౌర్ణమి)',
    festival_type: 'national',
    is_holiday: true,
    holiday_type: 'gazetted',
    importance: 'major',
    tag: 'purnima',
    description_en: 'Birth, enlightenment, and parinirvana of Gautama Buddha.',
    description_te: 'గౌతమ బుద్ధుని త్రివిధ పవిత్ర దినోత్సవం.',
  },

  // --- JUNE 2027 ---
  {
    id: 'f-2027-06-02',
    calendar_date: '2027-06-02',
    name_en: 'Telangana Formation Day',
    name_te: 'తెలంగాణ ఆవిర్భావ దినోత్సవం',
    festival_type: 'regional',
    is_holiday: true,
    holiday_type: 'regional_ap',
    importance: 'medium',
    tag: 'holiday',
    description_en: 'State formation day celebrated across Telangana.',
    description_te: 'తెలంగాణ రాష్ట్ర అవతరణ దినోత్సవం.',
  },
  {
    id: 'f-2027-06-15',
    calendar_date: '2027-06-15',
    name_en: 'Mithuna Sankranti',
    name_te: 'మిథున సంక్రాంతి',
    festival_type: 'hindu',
    importance: 'normal',
    tag: 'sankranti',
    description_en: 'Sun transit into Gemini.',
    description_te: 'సూర్యుడు మిథున రాశిలోకి ప్రవేశం.',
  },
  {
    id: 'f-2027-06-16',
    calendar_date: '2027-06-16',
    name_en: 'Nirjala Ekadashi',
    name_te: 'నిర్జల ఏకాదశి',
    festival_type: 'hindu',
    importance: 'major',
    tag: 'ekadashi',
    description_en: 'Most austere Ekadashi fast observed without water.',
    description_te: 'నీరు కూడా ముట్టకుండా ఆచరించే అత్యంత పవిత్ర నిర్జల ఏకాదశి.',
  },
  {
    id: 'f-2027-06-19',
    calendar_date: '2027-06-19',
    name_en: 'Eruvaka Purnima (Jyeshtha Purnima)',
    name_te: 'ఏరువాక పౌర్ణమి (జ్యేష్ఠ పౌర్ణమి)',
    festival_type: 'cultural',
    importance: 'medium',
    tag: 'purnima',
    description_en: 'Agricultural festival where Telugu farmers begin plowing fields for the kharif season.',
    description_te: 'రైతులు నాగలి, ఎడ్లను పూజించి వ్యవసాయ పనులు ప్రారంభించే ఏరువాక పున్నమి.',
  },

  // --- JULY 2027 ---
  {
    id: 'f-2027-07-04',
    calendar_date: '2027-07-04',
    name_en: 'Ashadha Amavasya',
    name_te: 'ఆషాఢ అమావాస్య (చుక్కల అమావాస్య)',
    festival_type: 'hindu',
    importance: 'normal',
    tag: 'amavasya',
    description_en: 'New moon of Ashadha month.',
    description_te: 'ఆషాఢ మాస అమావాస్య.',
  },
  {
    id: 'f-2027-07-15',
    calendar_date: '2027-07-15',
    name_en: 'Toli Ekadashi (Shayana Ekadashi)',
    name_te: 'తొలి ఏకాదశి (శయన ఏకాదశి)',
    festival_type: 'hindu',
    is_holiday: false,
    importance: 'major',
    tag: 'ekadashi',
    description_en: 'Lord Vishnu begins his cosmic sleep (Yoga Nidra); marks beginning of Chaturmasya.',
    description_te: 'చాతుర్మాస్య వ్రత ప్రారంభం మరియు శ్రీహరి యోగనిద్రలోకి ప్రవేశించే పవిత్ర తొలి ఏకాదశి.',
  },
  {
    id: 'f-2027-07-16',
    calendar_date: '2027-07-16',
    name_en: 'Karka Sankranti (Dakshinayana Begins)',
    name_te: 'కర్కటక సంక్రాంతి (దక్షిణాయన పుణ్యకాలం)',
    festival_type: 'hindu',
    importance: 'medium',
    tag: 'sankranti',
    description_en: 'Sun moves southward into Cancer; beginning of Dakshinayana.',
    description_te: 'సూర్యుడు కర్కాటక రాశిలోకి ప్రవేశించి దక్షిణాయనం ప్రారంభమయ్యే పుణ్యకాలం.',
  },
  {
    id: 'f-2027-07-19',
    calendar_date: '2027-07-19',
    name_en: 'Guru Purnima (Vyasa Purnima)',
    name_te: 'గురు పౌర్ణమి (వ్యాస పౌర్ణమి)',
    festival_type: 'hindu',
    importance: 'major',
    tag: 'purnima',
    description_en: 'Reverence to spiritual gurus and birth of sage Veda Vyasa.',
    description_te: 'వేదవ్యాస మహర్షి జయంతి మరియు గురువులను పూజించే మహోన్నత పర్వదినం.',
  },

  // --- AUGUST 2027 ---
  {
    id: 'f-2027-08-03',
    calendar_date: '2027-08-03',
    name_en: 'Polala Amavasya (Shravana Amavasya)',
    name_te: 'పోలాల అమావాస్య (శ్రావణ అమావాస్య)',
    festival_type: 'cultural',
    importance: 'medium',
    tag: 'amavasya',
    description_en: 'Traditional Telugu festival for protection and well-being of children.',
    description_te: 'పిల్లల ఆయురారోగ్యాల కోసం తల్లులు జరిపే పోలేరమ్మ వ్రతం.',
  },
  {
    id: 'f-2027-08-13',
    calendar_date: '2027-08-13',
    name_en: 'Varalakshmi Vratam',
    name_te: 'వరలక్ష్మీ వ్రతం',
    festival_type: 'hindu',
    is_holiday: true,
    holiday_type: 'regional_ap',
    importance: 'major',
    tag: 'festival',
    description_en: 'Sacred worship of Goddess Lakshmi by Telugu women on the Friday before Shravana Purnima.',
    description_te: 'శ్రావణ శుక్రవారం నాడు సౌభాగ్యం కోసం మహిళలు భక్తిశ్రద్ధలతో జరిపే వరలక్ష్మీ పూజ.',
  },
  {
    id: 'f-2027-08-15',
    calendar_date: '2027-08-15',
    name_en: 'Independence Day',
    name_te: 'భారత స్వాతంత్ర్య దినోత్సవం',
    festival_type: 'national',
    is_holiday: true,
    holiday_type: 'gazetted',
    importance: 'major',
    tag: 'holiday',
    description_en: 'National holiday commemorating Indian Independence in 1947.',
    description_te: 'భారత స్వాతంత్ర్య దినోత్సవ జాతీయ వేడుక.',
  },
  {
    id: 'f-2027-08-17',
    calendar_date: '2027-08-17',
    name_en: 'Raksha Bandhan / Jandhyala Purnima',
    name_te: 'రాఖీ పౌర్ణమి / జంధ్యాల పౌర్ణమి (రాఖీ పండుగ)',
    festival_type: 'hindu',
    is_holiday: true,
    holiday_type: 'restricted',
    importance: 'major',
    tag: 'purnima',
    description_en: 'Celebration of brotherhood and sacred thread renewal (Upakarma).',
    description_te: 'అన్నాచెల్లెళ్ల అనురాగ బంధం రాఖీ మరియు ఉపాకర్మ యజ్ఞోపవీత ధారణ.',
  },
  {
    id: 'f-2027-08-24',
    calendar_date: '2027-08-24',
    name_en: 'Sri Krishna Janmashtami (Gokulashtami)',
    name_te: 'శ్రీకృష్ణాష్టమి (గోకులాష్టమి)',
    festival_type: 'hindu',
    is_holiday: true,
    holiday_type: 'gazetted',
    importance: 'major',
    tag: 'festival',
    description_en: 'Grand celebration of Lord Sri Krishna birth with Utlotsavam.',
    description_te: 'బాలకృష్ణుని జన్మదినం, ఉట్లోత్సవాలు మరియు పూజలు.',
  },
  {
    id: 'f-2027-08-28',
    calendar_date: '2027-08-28',
    name_en: 'Aja Ekadashi',
    name_te: 'అజా ఏకాదశి',
    festival_type: 'hindu',
    importance: 'medium',
    tag: 'ekadashi',
    description_en: 'Shravana Krishna Ekadashi.',
    description_te: 'పాపనాశన అజా ఏకాదశి.',
  },

  // --- SEPTEMBER 2027 ---
  {
    id: 'f-2027-09-01',
    calendar_date: '2027-09-01',
    name_en: 'Bhadrapada Amavasya',
    name_te: 'భాద్రపద అమావాస్య',
    festival_type: 'hindu',
    importance: 'normal',
    tag: 'amavasya',
    description_en: 'New moon of Bhadrapada month.',
    description_te: 'భాద్రపద అమావాస్య.',
  },
  {
    id: 'f-2027-09-04',
    calendar_date: '2027-09-04',
    name_en: 'Vinayaka Chavithi (Ganesha Chaturthi)',
    name_te: 'వినాయక చవితి (గణేశ చతుర్థి)',
    festival_type: 'hindu',
    is_holiday: true,
    holiday_type: 'gazetted',
    importance: 'major',
    tag: 'festival',
    description_en: 'Grand 11-day celebration of Vignaharta Ganesha installed in mandapams across AP & Telangana.',
    description_te: 'విఘ్నేశ్వరుని ఆరాధన, మట్టి వినాయక పూజ మరియు నవరాత్రి ఉత్సవాలు.',
  },
  {
    id: 'f-2027-09-14',
    calendar_date: '2027-09-14',
    name_en: 'Anantha Padmanabha Vratam / Ganesha Immersion',
    name_te: 'అనంత పద్మనాభ వ్రతం / గణేష్ నిమజ్జనం',
    festival_type: 'hindu',
    importance: 'major',
    tag: 'festival',
    description_en: 'Anantha Padmanabha Swamy vrata and Ganesha Visarjan.',
    description_te: 'అనంత చతుర్దశి పూజ మరియు వినాయక నిమజ్జనం.',
  },
  {
    id: 'f-2027-09-16',
    calendar_date: '2027-09-16',
    name_en: 'Mahalaya Paksha Begins (Bhadrapada Purnima)',
    name_te: 'మహాలయ పక్షారంభం (భాద్రపద పౌర్ణమి)',
    festival_type: 'hindu',
    importance: 'medium',
    tag: 'purnima',
    description_en: 'Beginning of the 15-day fortnight dedicated to ancestral rituals (Pitru Paksha).',
    description_te: 'పితృదేవతల ఆరాధనకు అంకితమైన మహాలయ పక్షం ప్రారంభం.',
  },
  {
    id: 'f-2027-09-26',
    calendar_date: '2027-09-26',
    name_en: 'Indira Ekadashi',
    name_te: 'ఇందిరా ఏకాదశి',
    festival_type: 'hindu',
    importance: 'medium',
    tag: 'ekadashi',
    description_en: 'Mahalaya Paksha Ekadashi helping ancestors attain salvation.',
    description_te: 'పితృదేవతలకు సద్గతి ప్రసాదించే ఇందిరా ఏకాదశి.',
  },
  {
    id: 'f-2027-09-30',
    calendar_date: '2027-09-30',
    name_en: 'Mahalaya Amavasya (Peddala Amavasya)',
    name_te: 'మహాలయ అమావాస్య (పెద్దల అమావాస్య)',
    festival_type: 'hindu',
    is_holiday: true,
    holiday_type: 'restricted',
    importance: 'major',
    tag: 'amavasya',
    description_en: 'Most sacred day for performing Tarpanam and charity for ancestors.',
    description_te: 'పితృ తర్పణాలు మరియు పిండ ప్రదానాలు ఆచరించే అత్యంత పవిత్ర మహాలయ అమావాస్య.',
  },
  {
    id: 'f-2027-09-30-b',
    calendar_date: '2027-09-30',
    name_en: 'Bathukamma Festival Starts',
    name_te: 'ఎంగిలిపూల బతుకమ్మ (బతుకమ్మ ప్రారంభం)',
    festival_type: 'regional',
    importance: 'major',
    tag: 'festival',
    description_en: 'First day of floral festival celebrated with colorful seasonal flowers.',
    description_te: 'తెలంగాణ సంస్కృతిని ప్రతిబింబించే తీరొక్క పూల పండుగ బతుకమ్మ ప్రారంభం.',
  },

  // --- OCTOBER 2027 ---
  {
    id: 'f-2027-10-01',
    calendar_date: '2027-10-01',
    name_en: 'Devi Sharannavaratri Begins (Kalasha Sthapana)',
    name_te: 'దేవీ శరన్నవరాత్రులు ప్రారంభం (కలశ స్థాపన)',
    festival_type: 'hindu',
    importance: 'major',
    tag: 'festival',
    description_en: 'Beginning of the 9-day Navaratri worship of Goddess Kanaka Durga in Vijayawada and across temples.',
    description_te: 'విజయవాడ ఇంద్రకీలాద్రిపై కనకదుర్గమ్మ దివ్య నవరాత్రుల ప్రారంభం.',
  },
  {
    id: 'f-2027-10-02',
    calendar_date: '2027-10-02',
    name_en: 'Mahatma Gandhi Jayanti',
    name_te: 'మహాత్మా గాంధీ జయంతి',
    festival_type: 'national',
    is_holiday: true,
    holiday_type: 'gazetted',
    importance: 'major',
    tag: 'holiday',
    description_en: 'National holiday celebrating the Father of the Nation.',
    description_te: 'జాతిపిత మహాత్మా గాంధీ జయంతి జాతీయ దినోత్సవం.',
  },
  {
    id: 'f-2027-10-08',
    calendar_date: '2027-10-08',
    name_en: 'Durgashtami / Bathukamma Saddula',
    name_te: 'దుర్గాష్టమి (సద్దుల బతుకమ్మ)',
    festival_type: 'hindu',
    is_holiday: true,
    holiday_type: 'gazetted',
    importance: 'major',
    tag: 'festival',
    description_en: 'Worship of Goddess Durga and grand climax of Bathukamma floral celebrations.',
    description_te: 'మహాష్టమి దుర్గాపూజ మరియు సద్దుల బతుకమ్మ సంబరాలు.',
  },
  {
    id: 'f-2027-10-09',
    calendar_date: '2027-10-09',
    name_en: 'Mahanavami / Ayudha Puja',
    name_te: 'మహార్నవమి / ఆయుధ పూజ',
    festival_type: 'hindu',
    is_holiday: false,
    importance: 'major',
    tag: 'festival',
    description_en: 'Worship of vehicles, tools, instruments, and Goddess Saraswati.',
    description_te: 'వాహనాలు, పనిముట్లను పూజించే పవిత్ర ఆయుధ పూజ.',
  },
  {
    id: 'f-2027-10-10',
    calendar_date: '2027-10-10',
    name_en: 'Vijaya Dashami / Dasara',
    name_te: 'విజయదశమి / దసరా',
    festival_type: 'hindu',
    is_holiday: true,
    holiday_type: 'gazetted',
    importance: 'major',
    tag: 'festival',
    description_en: 'Triumph of Goddess Durga over Mahishasura; Shami puja and Jami tree worship for victory.',
    description_te: 'చెడుపై మంచి సాధించిన విజయానికి ప్రతీకగా జమ్మిచెట్టు పూజ మరియు విజయదశమి పర్వదినం.',
  },
  {
    id: 'f-2027-10-15',
    calendar_date: '2027-10-15',
    name_en: 'Sharad Purnima (Kojagari Purnima)',
    name_te: 'శరత్ పౌర్ణమి (కొజాగరి పౌర్ణమి)',
    festival_type: 'hindu',
    importance: 'medium',
    tag: 'purnima',
    description_en: 'Harvest full moon dedicated to Lord Krishna Raas Leela and Goddess Lakshmi.',
    description_te: 'అమృతవర్షపు వెన్నెల రాత్రి శరత్ పౌర్ణమి.',
  },
  {
    id: 'f-2027-10-26',
    calendar_date: '2027-10-26',
    name_en: 'Rama Ekadashi',
    name_te: 'రమా ఏకాదశి',
    festival_type: 'hindu',
    importance: 'medium',
    tag: 'ekadashi',
    description_en: 'Kartika Krishna Ekadashi.',
    description_te: 'కార్తీక కృష్ణ ఏకాదశి వ్రతం.',
  },
  {
    id: 'f-2027-10-28',
    calendar_date: '2027-10-28',
    name_en: 'Dhanteras (Dhanatrayodashi)',
    name_te: 'ధన త్రయోదశి (ధన్‌తేరస్)',
    festival_type: 'hindu',
    importance: 'major',
    tag: 'festival',
    description_en: 'Auspicious day for gold, silver, and utensil purchases invoking Dhanvantari.',
    description_te: 'ధన్వంతరి జయంతి మరియు బంగారం, వెండి కొనుగోళ్లకు శుభదినం.',
  },
  {
    id: 'f-2027-10-29',
    calendar_date: '2027-10-29',
    name_en: 'Naraka Chaturdashi / Deepavali Festival',
    name_te: 'నరక చతుర్దశి / దీపావళి పండుగ',
    festival_type: 'hindu',
    is_holiday: true,
    holiday_type: 'gazetted',
    importance: 'major',
    tag: 'festival',
    description_en: 'Celebration of triumph over Narakasura with oil bath, crackers, and lamps.',
    description_te: 'నరకాసుర వధ స్మరణ, దీపాల కాంతులు మరియు టపాసుల సంబరం.',
  },
  {
    id: 'f-2027-10-30',
    calendar_date: '2027-10-30',
    name_en: 'Deepavali Lakshmi Puja (Karthika Amavasya)',
    name_te: 'దీపావళి లక్ష్మీ పూజ (కేదారేశ్వర వ్రతం)',
    festival_type: 'hindu',
    is_holiday: true,
    holiday_type: 'gazetted',
    importance: 'major',
    tag: 'amavasya',
    description_en: 'Worship of Goddess Mahalakshmi on Amavasya evening; Kedareswara Vratam.',
    description_te: 'ధనలక్ష్మి పూజ మరియు కేదారేశ్వర స్వామి నోము.',
  },

  // --- NOVEMBER 2027 ---
  {
    id: 'f-2027-11-01',
    calendar_date: '2027-11-01',
    name_en: 'Andhra Pradesh Formation Day',
    name_te: 'ఆంధ్రప్రదేశ్ అవతరణ దినోత్సవం',
    festival_type: 'regional',
    is_holiday: true,
    holiday_type: 'regional_ap',
    importance: 'medium',
    tag: 'holiday',
    description_en: 'State formation anniversary of Andhra Pradesh.',
    description_te: 'ఆంధ్రప్రదేశ్ రాష్ట్ర అవతరణ దినం.',
  },
  {
    id: 'f-2027-11-09',
    calendar_date: '2027-11-09',
    name_en: 'Nagula Chavithi',
    name_te: 'నాగుల చవితి',
    festival_type: 'regional',
    is_holiday: false,
    importance: 'major',
    tag: 'festival',
    description_en: 'Sacred worship of the Serpent God Naga Devata at anthills with milk and chimmili in AP & Telangana.',
    description_te: 'పుట్టలో పాలుపోసి నాగదేవతను భక్తితో ఆరాధించే పవిత్ర పండుగ.',
  },
  {
    id: 'f-2027-11-13',
    calendar_date: '2027-11-13',
    name_en: 'Karthika Purnima / Jwala Thoranam',
    name_te: 'కార్తీక పౌర్ణమి / జ్వాలాతోరణం',
    festival_type: 'hindu',
    is_holiday: true,
    holiday_type: 'gazetted',
    importance: 'major',
    tag: 'purnima',
    description_en: 'Most sacred Karthika month full moon; 365 wicks lighting, Shiva temple deepotsavam, and Jwala Thoranam.',
    description_te: '365 వత్తుల దీపాలు, ఉసిరి చెట్టు పూజ మరియు జ్వాలాతోరణ దర్శనం.',
  },
  {
    id: 'f-2027-11-24',
    calendar_date: '2027-11-24',
    name_en: 'Utpanna Ekadashi',
    name_te: 'ఉత్పన్న ఏకాదశి',
    festival_type: 'hindu',
    importance: 'medium',
    tag: 'ekadashi',
    description_en: 'Origin day of Ekadashi Devi from Lord Vishnu.',
    description_te: 'ఏకాదశి దేవి ఆవిర్భావ దినం.',
  },
  {
    id: 'f-2027-11-28',
    calendar_date: '2027-11-28',
    name_en: 'Karthika Amavasya (Poli Swargam)',
    name_te: 'కార్తీక అమావాస్య (పోలి స్వర్గం)',
    festival_type: 'regional',
    importance: 'medium',
    tag: 'amavasya',
    description_en: 'Traditional Poli Swargam deepam release in waters concluding holy Karthika month.',
    description_te: 'కార్తీక మాస దీపాలను నీటిలో వదిలే పోలిపాడ్యమి / పోలి స్వర్గం నోము.',
  },

  // --- DECEMBER 2027 ---
  {
    id: 'f-2027-12-09',
    calendar_date: '2027-12-09',
    name_en: 'Gita Jayanti / Mokshada Ekadashi',
    name_te: 'గీతా జయంతి / మోక్షద ఏకాదశి',
    festival_type: 'hindu',
    importance: 'major',
    tag: 'ekadashi',
    description_en: 'Delivery of Bhagavad Gita by Lord Krishna to Arjuna at Kurukshetra.',
    description_te: 'కురుక్షేత్రంలో శ్రీకృష్ణుడు గీతాబోధ చేసిన పవిత్ర గీతా జయంతి.',
  },
  {
    id: 'f-2027-12-13',
    calendar_date: '2027-12-13',
    name_en: 'Dattatreya Jayanti (Margashirsha Purnima)',
    name_te: 'దత్తాత్రేయ జయంతి (మార్గశిర పౌర్ణమి)',
    festival_type: 'hindu',
    importance: 'major',
    tag: 'purnima',
    description_en: 'Appearance day of Lord Dattatreya, embodiment of the Trinity.',
    description_te: 'త్రిమూర్తి స్వరూపుడైన శ్రీ దత్తాత్రేయ స్వామి జన్మదినం.',
  },
  {
    id: 'f-2027-12-16',
    calendar_date: '2027-12-16',
    name_en: 'Dhanurmasam Begins',
    name_te: 'ధనుర్మాసారంభం (తిరుప్పావై ప్రారంభం)',
    festival_type: 'regional',
    importance: 'medium',
    tag: 'festival',
    description_en: 'Beginning of sacred Dhanurmasam with Goda Devi Tiruppavai recitations.',
    description_te: 'శ్రీ విష్ణు ఆలయాల్లో గోదాదేవి తిరుప్పావై పారాయణం ప్రారంభం.',
  },
  {
    id: 'f-2027-12-20',
    calendar_date: '2027-12-20',
    name_en: 'Vaikuntha Ekadashi (Mukkoti Ekadashi)',
    name_te: 'వైకుంఠ ఏకాదశి (ముక్కోటి ఏకాదశి)',
    festival_type: 'hindu',
    is_holiday: true,
    holiday_type: 'regional_ap',
    importance: 'major',
    tag: 'ekadashi',
    description_en: 'Opening of the Northern Gateway (Uttara Dwara Darshanam) in Tirumala and Vishnu temples worldwide.',
    description_te: 'తిరుమల సహా వైష్ణవ దివ్యక్షేత్రాలలో ఉత్తర ద్వార దర్శనం లభించే పరమ పవిత్ర ముక్కోటి ఏకాదశి.',
  },
  {
    id: 'f-2027-12-25',
    calendar_date: '2027-12-25',
    name_en: 'Christmas',
    name_te: 'క్రిస్మస్ పండుగ',
    festival_type: 'national',
    is_holiday: true,
    holiday_type: 'gazetted',
    importance: 'major',
    tag: 'holiday',
    description_en: 'Celebration of the Nativity of Jesus Christ.',
    description_te: 'యేసుక్రీస్తు జన్మదిన వేడుక.',
  },
  {
    id: 'f-2027-12-28',
    calendar_date: '2027-12-28',
    name_en: 'Margashirsha Amavasya (Hanumad Vratam)',
    name_te: 'మార్గశిర అమావాస్య (హనుమద్వ్రతం)',
    festival_type: 'hindu',
    importance: 'medium',
    tag: 'amavasya',
    description_en: 'Traditional Hanumad Vrata fast.',
    description_te: 'హనుమద్వ్రత ఆచరణ మరియు అమావాస్య తర్పణాలు.',
  },
];
